version: '3.9'
services: 

  nginx:
    image: nginx:alpine
    restart: always
    container_name: lcs_nginx
    ports:
      - 8000:80   
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/logs/nginx    
    networks:
      - dev-network

php:
  build:
    args:
    user: root
    uid: 1000
    context: ./
    dockerfile: Dockerfile
  container_name: lcs_php
  restart: always
  working_dir: /var/www/html/
  volumes:
    - ./:/var/www/html
  depends_on: 
    - redis
    - queue  
  networks:
    - dev-network

queue:
  build: 
    args: 
    user: carlos
    uid: 1000
    context: ./
    dockerfile: Dockerfile
    restart: always
    command: "php artisan queue:work"
    volumes: 
      - ./:/var/www
    depends_on: 
      - redis
    networks: 
      - dev-network

redis:
  args: 
  user: root
  uid: 1000  
  image: redis:latest
  restart: always
  networks:
    - dev-network

postgres:
  args: 
  user: root
  uid: 1000
  image: postgres:12.3-alpine
  container_name: lcs_postgres
  restart: always
  ports:
    - 5432:5432
  volumes:
    - ./docker/postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: 123456
    POSTGRES_DB: lcs
    POSTGRES_HOST_AUTH_METHOD: trust
  networks:
    - dev-network

networks: 
  dev-network:
    driver: bridge  